# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-18 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mydashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.IntegerField()),
                ('registered_date', models.DateTimeField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydashboard.Report')),
            ],
        ),
    ]
